version: '3'

services:
  user:
    container_name: user
    build: 
      context: .
      dockerfile: user.Dockerfile
    ports:
      - "8081:8081"
    networks:
      - red
    command: grunt testUser
  event:
    container_name: event
    build: 
      context: .
      dockerfile: event.Dockerfile
    ports:
      - "8082:8082"
    networks:
      - red  
    command: grunt testEvent  
  info:
    container_name: info
    build: 
      context: .
      dockerfile: info.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - red
    command: grunt testInfo
 

networks:
  red:
    driver: bridge
