--- 
jobs: 
  install: 
    steps: 
      - checkout
      - 
        run: "npm install"
  test: 
    steps: 
      - checkout
      - 
        run: "grunt test"
version: 2.1
workflows: 
  install_and_test: 
    jobs: 
      - install
      - test

