--- 
jobs: 
  build: 
    docker: 
      - image: anogueras/lgtbclub:latest
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD
    steps:
      - run: 
          name: Run tests
          command: docker run --rm -t anogueras/lgtbclub
     
version: 2.1
workflows: 
  build_and_test: 
    jobs: 
      - build

