name: Publicar la imagen Docker en un paquete de GitHub
on: push
jobs:
  push_to_registry:
    name: Publicar la imagen Docker a GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Comprobar el repo
        uses: actions/checkout@v2
      - name: Publicar a GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lgtbclub/lgtbclub:latest

